### PR TITLE
support variable mask lengths

### PR DESCRIPTION
**Pull request by maxvw**
This PR introduces some improvements in the auto formatting functionality. Some countries have variable number lengths, so just giving 1 mask is not enough. Now we attempt to load all possible formatting rules and give them to the JavaScript code, which will then use the nearest-match (based on length) to format the given input. As for leading zeros, the code has switched to using international syntax instead of national. This does mean some formatting may appear different, for example in the U.S. this results in `(555) 555-5555` (national) now being formatted as `555-55-55-555` (international).

I have also started with some [front-end tests](https://github.com/whitepaperclip/live_phone/issues/9) using [hound](https://github.com/HashNuke/hound). It's just a few now but it's a good starting point I think.

### CODE REVIEW

**Comment by whitepaperclip** [comment]
Looks good, thanks! I'm gonna play around with this a bit. Can we get chromedriver installed in the CI as well?

**Comment by maxvw** [comment]
Maybe with https://github.com/marketplace/actions/setup-chromedriver?

**Comment by whitepaperclip** [comment]
K, I added it to the workflow. Seems to be working!

**Comment by maxvw** [comment]
Be sure to run the tests with `mix test --include browser` on CI otherwise it doesn't use the chromedriver tests. I disabled them by default because chromedriver isn't always available

**Pull request merged**
